name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inspect runner
        run: |
            echo "Hello from GitHub Actions!"
            echo "Operating system:"
            uname -a
            echo "Current directory:"
            pwd
            echo "User:"
            whoami
            echo "Files:"
            ls -la